# Generated by Django 2.1.7 on 2021-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(default='', max_length=10, verbose_name='Customer')),
                ('Project', models.CharField(default='', max_length=100, verbose_name='Project')),
                ('Unit', models.CharField(default='', max_length=100, verbose_name='Unit')),
                ('Phase', models.CharField(default='', max_length=10, verbose_name='Phase')),
                ('Testitem', models.CharField(default='', max_length=100, verbose_name='Testitem')),
                ('Item_Des', models.CharField(default='', max_length=500, verbose_name='Item_Des')),
                ('Tester', models.CharField(default='', max_length=20, verbose_name='Tester')),
                ('Comments', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comments')),
                ('Start_time', models.CharField(blank=True, default='', max_length=26, verbose_name='Start_time')),
                ('End_time', models.CharField(blank=True, default='', max_length=26, verbose_name='End_time')),
                ('Result_time', models.CharField(blank=True, default='', max_length=26, verbose_name='Result_time')),
                ('Result', models.CharField(blank=True, default='', max_length=26, verbose_name='Result')),
            ],
            options={
                'verbose_name': 'TestLog',
                'verbose_name_plural': 'TestLog',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(default='', max_length=20, verbose_name='Account')),
                ('Password', models.CharField(default='', max_length=256, verbose_name='Password')),
                ('Username', models.CharField(default='', max_length=20, unique=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
    ]
